root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/vapor-server ./cmd/vapor-server"
bin = "./tmp/vapor-server"
full_bin = "./tmp/vapor-server"
include_ext = ["go"]
exclude_dir = ["tmp", ".git"]
delay = 200
stop_on_error = true

[log]
time = true
